version: '3.1'
services:
  app:
    Build: .
    image: calculadora-app:latest
    deploy: 
      replicas: 3
      update_config:
        parallelims: 2
        delay: 4s
      restart_policy:
        condition: on-failure
